safe: true
incremental: true
full_rebuild: false
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
defaults:
  -
    scope:
      path:            "**/*.*"
    values:
      sitemap:         true
 
