include:
  - page-build/site-source-pagesjekyll-ftw
  - _site
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
defaults:
  -
    scope:
      path:            "**/*.*"
    values:
      sitemap:         true
 
