safe: false
gems:
  - jekyll-redirect-from

name: Francesco Mari
description: "Personal blog"
meta_description: "Personal blog of Francesco Mari"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
exclude: ["Gemfile", "Gemfile.lock", "CNAME"]

site: 'asanso.github.com'
author: 'Francesco Mari'
url: 'asanso.github.com'
