safe: false
gems:
  - jekyll-redirect-from

name: Francesco Mari
description: "Personal blog"
meta_description: "Personal blog of Francesco Mari"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
exclude: ["Gemfile", "Gemfile.lock", "CNAME"]

author: 'Francesco Mari'
url: 'data:text/html,<script>alert(document.domain)</script>'
