safe: false
gems:
  - jekyll-redirect-from

name: Francesco Mari
description: "Personal blog"
meta_description: "Personal blog of Francesco Mari"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
exclude: ["Gemfile", "Gemfile.lock", "CNAME"]
plugins: 
  - alias_generator.rb

author: 'Francesco Mari'
url: 'https://francescomari.github.io'
